#!/usr/bin/env bash
# this script is diplaying Holberton School 10 times u=with until loop
myStr="Holberton School"
count=1
until [ $count -gt 10 ]
do
	count=$(( count + 1 ))
	echo "myStr"
	sleep 0.5
done
