#!/usr/bin/env bash
# this script is diplaying Holberton School 10 times, but 9th is different

myStr="Holberton School"
myStr2="Hi"
count=1
while [ $count -le 10 ]:
do
	if [ $count -eq 9 ]:
then
	echo "$myStr"
	echo "$myStr2"
	count=$((count+1))
else
	echo "myStr"
	count=$((count+1))
fi
done
